# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Home Assistant ownCloud Server
version: "0.1.0"
slug: owncloud
description: ownCloud container running in Home Assistant
url: "https://github.com/home-assistant/addons-example/tree/main"
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-example"
